FROM rustembedded/cross:x86_64-unknown-linux-gnu-0.2.1

RUN apt-get update && \
    apt-get install -y libc6 \
    libclang-dev \
    libgtk-3-dev \
    libxcb-render0-dev \
    libxcb-shape0-dev \
    libxcb-xfixes0-dev \
    libxkbcommon-dev \
    libssl-dev \
    software-properties-common && \
    cmake \
    pkg-config \
    libfreetype6-dev \
    libfontconfig1-dev \
    libxkbcommon-dev \
    python3 \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# for glibc-2.25
RUN add-apt-repository 'deb [arch=amd64] http://mirrors.kernel.org/ubuntu/ jammy main'