[package]
name = "mtechserver_two"
version = "0.1.0"
edition = "2021"

[dependencies]
database = { workspace=true }
anyhow = { workspace=true }
log  = { workspace=true }
serde = { workspace=true }
surrealdb = { workspace=true }
chrono = { workspace=true }
my_proc_macros = { path = "../my_proc_macros" }

egui ={ version="0.27.2", features = ["persistence"]} # "callstack", "log"
eframe = { version="0.27.2", default-features = false, features=["wgpu"] }
wasm-bindgen = "0.2.92"
egui_extras = { version = "0.27.2", features = ["datepicker"]}
egui-aesthetix = { version = "0.2.3", features = ["carl"] }
egui_dock = "0.12.0"
ratframe = "1"
ratatui = { version = "0.26.3", default-features = false }
web-time = "1.1.0"
wasm-bindgen-futures = "0.4"
crossbeam = "0.8.4"
console_error_panic_hook = "0.1.7"
gloo-worker = "0.5.0"
futures = "0.3.30"
egui-toast = "0.13.0"
wasm-cookies = { version= "0.2.1" }
serde_json = "1.0.117"
egui_form = {version="0.1.1", features = ["validator_validator"]}
egui_animation = "0.4.0"
egui_infinite_scroll = "0.3.0"
egui_inbox = "0.4.1"
egui_ratatui = "0.0.5"


# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11.3"
# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"

# [profile.release]
# opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
# [profile.dev.package."*"]
# opt-level = 2
# 
[[bin]]
name = "dummy_worker"
path = "src/dummy_worker.rs"
