[package]
name = "mtechserver"
version = "0.1.0"
edition = "2021"

[dependencies]
database = { workspace=true }
anyhow = { workspace=true }
log  = { workspace=true }
serde = { workspace=true }
surrealdb = { workspace=true }
chrono = { workspace=true }

egui ={ version="0.27", features = ["persistence"]} # "callstack", "log"
eframe = { version="0.27", default-features = false, features=["wgpu"] }
wasm-bindgen = "0.2"
egui_extras = { version = "0.27", features = ["datepicker"]}
egui-aesthetix = { version = "0.2", features = ["carl"] }
egui_dock = "0.12"
ratframe = "1"
ratatui = { version = "0.26", default-features = false }
web-time = "1.1"
wasm-bindgen-futures = "0.4"
crossbeam = "0.8"
console_error_panic_hook = "0.1"
gloo-worker = "0.5"
futures = "0.3"
egui-toast = "0.13"
wasm-cookies = { version= "0.2" }
serde_json = "1"
egui_form = {version="0.1", features = ["validator_validator"]}
egui_animation = "0.4"
egui_infinite_scroll = "0.3"
egui_inbox = "0.4"
egui_ratatui = "0.0.5"


# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11.3"
# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"

# [profile.release]
# opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
# [profile.dev.package."*"]
# opt-level = 2
# 
[[bin]]
name = "dummy_worker"
path = "src/dummy_worker.rs"
