[workspace]
resolver = "2"
members=["frontend", "database" ] #"my_proc_macros"


[workspace.dependencies]
database = { path = "database" }
serde = { version = "1.0.198", features = ["derive"] }
surrealdb = { version = "1.5.1", features = ["protocol-ws"] } # kv-speedb "protocol-http", "native-tls"
anyhow = "1"
log="0.4"
chrono = "0.4.38"
