[workspace]
resolver = "2"
members = [ "MtechServer2.0", "database" , "displays", "Mastertech4.0", "websocket_server"] 

[workspace.dependencies]
# displays = { path = "displays" }
database = { path = "database" }
eframe = { version="0.28", features=["persistence", "serde", "wgpu", "default_fonts"] } # wgpu
egui_extras = { version = "0.28", features = ["datepicker"]}
# surrealdb = { version = "1.5", features = ["protocol-ws"] } # kv-speedb "protocol-http", "native-tls"
surrealdb-alpha = { version="=2.0.7", features = ["protocol-ws"] }
egui_dock = { version = "0.13", features = ["serde"]}
tokio = { version = "1", features = ["full", "tracing"] }
serde = { version = "1", features = ["derive"] }
ratatui = { version = "0.28", default-features = false }
structdiff = {version = "0.7", features = ["rustc_hash"]}
wasm-bindgen = "0.2"
web-time = "1"
wasm-bindgen-futures = "0.4"
log="0.4"
chrono = "0.4"
dotenv = "0.15"
serde_json = "1"
anyhow = "1"
ratframe = "1"
mime_guess = "2"
crossbeam = "0.8"
futures = "0.3"
fuzzy-matcher = "0.3"
uuid = { version = "1.10", features = ["v4"] } # Note: Version is slightly different but `uuid` is common
bincode = "1.3"
rfd = "0.14"
regex = "1.10"
async-trait = "0.1"
once_cell = "1.19.0"
simplelog = "0.12"
bytes = "1.7"

[profile.dev]
debug = true
lto = false
strip = false