services:
  mtechserver:
    image: shadowbrok3r/mtechserver:beta
    build:
      context: .
      dockerfile: ./Dockerfile
    develop:
      watch:
        - action: sync+restart
          path: ./MtechServer2.0
          target: /MtechServer2.0
          # ignore:
          #   - target/
        - action: rebuild
          path: Cargo.toml
    restart: always
    networks:
        - web
    ports:
      - 8080:8080
    expose:
      - 8080
    # volumes:
    #   - "${PWD}:${PWD}"

  websocketserver:
    image: shadowbrok3r/websocket_server:beta
    build:
      context: .
      dockerfile: ./websocket_server2/Dockerfile
    restart: always
    networks:
      - web
    ports:
      - 8081:8081
    expose:
      - 8081


networks:
  web:
    driver: bridge
    name: web