spin_manifest_version = 2

[application]
name = "mtechserver"
version = "0.1.0"


[[trigger.http]]
route = "/..."
component = "mtechserver"

[component.lean-cluster]
source = "target/wasm32-unknown-unknown/debug/mtechserver.wasm"
allowed_outbound_hosts = []
[component.lean-cluster.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]


