[package]
name = "websocket_server2"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8", features = ["ws"]}
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v4"] }
tracing-subscriber = "0.3.19"
tracing = "0.1.41"
futures = "0.3"
anyhow = "1"
log = "0.4"

# serde = { workspace = true }
surrealdb = { workspace = true }
database = { workspace = true }
chrono = { workspace = true }