[package]
name = "MasterTech"
version = "4.2.1"
edition = "2021"
description = "Mastertech"
build = "build.rs"

[features]
default = [ "gui", "inline", "term" ]
gui = [ "dep:eframe" ]
term = ["dep:tui-input", "dep:tui-textarea", "dep:ratatui"]
inline = []
# default=["winit"]   # , "cpu_fix", "compat_mode"
# winit = ["dep:egui-winit"]
# compat_mode = ["dep:egui_skia", "dep:egui-winit", "dep:softbuffer", "dep:skia-safe"] cpu_fix = []

[dependencies]
displays = { path="../displays", features = ["tokio"] }
reqwest = { version = "0.12", features = ["json", "stream", "cookies", "brotli"] }
ratatui = { version = "0.28.0", features = ["crossterm"], optional = true }
tui-input = { version = "0.10.0", features = ["crossterm"], optional = true}
tui-textarea = { version = "0.6.1", optional = true}
sysinfo = "0.31"
console-subscriber = "0.4.0"
futures-util = "0.3"
walkdir = "2.5"
pollster = "0.3"
image = "0.25"
egui_file = "0.18"
num-format = "0.4"
fs_extra = "1.3"
rayon = "1.10"
quick-xml = { version="0.36", features = ["serialize"] }
serde-xml-rs = "0.6"
num-traits = "0.2"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = "0.3"
rust-embed="8.4"
clap = { version = "4.5", features = ["derive"] }
dotenv = "0.15"
lettre = "0.11"
shell-words = "1"
reqwest_cookie_store = "0.8"
sha2 = { version = "0.10", features = ["std"] }
wmi = "0.13"
quickxml_to_serde = "0.6"
memmap2 = "0.9"
breakpad-symbols = { version = "0.22" }
minidump = { version = "0.22" }
minidump-common = { version = "0.22" }
minidump-processor = { version = "0.22", features = ["http"] }
minidump-unwind = "0.22"
linked-hash-map = "0.5"
ewebsock = { version = "0.6", features = [ "tls" ] }
hex = "0.4.3"
ring = "0.17.8"
egui_tracing = "0.2.2"
rust-s3 = "0.34"


# eframe = { version="0.28", features=["persistence", "serde", "default_fonts"] } 
eframe = { workspace=true, optional = true }
database = { workspace=true }
surrealdb-alpha = { workspace=true }
# surrealdb = { workspace=true }
tokio = { workspace=true }
serde_json = { workspace=true }
serde = { workspace=true }
log  = { workspace=true }
bytes = { workspace=true }
egui_extras = { workspace=true }
egui_dock = { workspace=true }
anyhow = { workspace=true }
ratframe = { workspace=true }
crossbeam = { workspace=true }
futures = { workspace=true }
# egui_ratatui = { workspace=true }
fuzzy-matcher = { workspace=true }
uuid = { workspace=true }
bincode = { workspace=true }
rfd = { workspace=true }
regex = { workspace=true }
chrono = { workspace=true }
simplelog = { workspace=true }
async-trait = { workspace=true }
once_cell = { workspace=true }

# egui_skia = { version = "0.4.0", features = ["winit", "cpu_fix"], optional = true}
# egui-winit = { ver1.0.86 "0.27.2", optional = true, default-features = false }
# softbuffer = {version = "0.4.2", optional = true}
# skia-safe = {version = "0.73.0", optional = true}
# portable-pty = "0.8.1"
# windows_x86_64_msvc
# known-folders 
# robocopyrs 
# planif = "0.2"
# tui-term = "0.1.11"

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio"]}

[[bench]]
name = "file_copy_benchmark"
harness = false


# [target.'cfg(target_os = "linux")'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }
openssl-sys = "0.9"
# libatasmart = "0.3.1"

[profile.release]
strip = "debuginfo"
debug = false
opt-level = 3

[profile.dev]
debug = true
lto = false
strip = false

[target.'cfg(target_os = "windows")'.build-dependencies]
static_vcruntime = "2"
embed-resource = "2.4"
winres = "0.1"
# embed-manifest = "1.4.0"

[package.metadata]
icon = ["D:/Users/Owner/Documents/GitHub/Mastertech4.0/src/assets/masterlogoV2.ico"]
resources = ["src/assets/**/*png", "src/assets/**/*ico"]

[package.metadata.winres]
ProductName = "Mastertech" 
OriginalFilename = "Mastertech.EXE"
LegalCopyright = "Copyright © 2024"
ProductVersion = "4.2.1"
FileDescription = "Mastertech"
