[package]
name = "MasterTech"
version = "4.4.9"
edition = "2024"
description = "Mastertech"
build = "build.rs"

[package.metadata.winres]
ProductName = "Mastertech" 
OriginalFilename = "Mastertech.EXE"
LegalCopyright = "Copyright © 2025"
ProductVersion = "4.4.9"
FileDescription = "Mastertech"

[features]
default = [ "inline" ]
inline = []

[dependencies]
eframe = { version="0.32.0", features=["persistence", "serde",  "default_fonts", "glow", "x11"], default-features=false}
displays = { path="../displays", features = ["tokio"] }
reqwest = { version = "0.12", features = ["json", "stream", "cookies", "brotli"] }
tui-textarea = { version = "0.7"}
sysinfo = {version = "0.36.0", features = ["serde", "multithread"]}
console-subscriber = "0.4"
futures-util = "0.3"
walkdir = "2.5"
pollster = "0.4"
image = "0.25"
egui_file = "0.22"
num-format = "0.4"
fs_extra = "1.3"
rayon = "1"
quick-xml = { version="0.38.0", features = ["serialize"] }
num-traits = "0.2"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = "0.3"
rust-embed="8.4"
clap = { version = "4.5", features = ["derive"] }
dotenv = "0.15"
shell-words = "1"
sha2 = { version = "0.10", features = ["std"] }
linked-hash-map = "0.5"
ewebsock = { git = "https://github.com/shadowbrok3r/ewebsock.git", version = "0.9.3", features = ["tokio", "tls", "rustls_ring"]} # , 
hex = "0.4.3"
ring = "0.17.14"
rust-s3 = "0.35"
semver = "1.0.23"
nvml-wrapper = { version = "0.11.0", features = ["serde"] }
lazy_static = "1.5.0"
# planif = "1"
ratatui-splash-screen = "0.1.4"
tui-scrollview = "0.5.1"
tachyonfx = "0.12.0"
powershell_script = "1.1.0"
color-eyre = "0.6.3"
itertools = "0.14.0"
unicode-width = "=0.2.0"
bit-set = "0.8.0"
tui-logger = "0.17"
arboard = "3"
tempfile = "3.19"
strum = { version = "0.27.1", features = ["strum_macros", "derive"] }
# nvme = "0.2.2"
rmcp = { version = "0.2.1", features = ["server", "transport-sse-server", "transport-io", "schemars"]}
xcap = "0.6.0"
display-info = "0.5.4"
enigo = { version = "0.5.0", features = ["serde"] }
self-replace = "1.5.0"
zstd = "0.13.3"
humansize = "2"
multi_log = "0.1"
env_logger = "*"

# surrealdb-alpha ={ workspace = true }
surrealdb = { workspace=true }
egui-data-table = { workspace = true }
egui_logger = {workspace = true }
ratatui = { workspace = true }
database = { workspace=true }
tokio = { workspace=true }
serde_json = { workspace=true }
serde = { workspace=true }
log  = { workspace=true }
bytes = { workspace=true }
egui_extras = { workspace=true }
egui_dock = { workspace=true }
anyhow = { workspace=true }
crossbeam = { workspace=true }
futures = { workspace=true }
structdiff = { workspace=true }
fuzzy-matcher = { workspace=true }
uuid = { workspace=true }
bincode = { workspace=true }
rfd = { workspace=true }
regex = { workspace=true }
chrono = { workspace=true }
simplelog = { workspace=true }
async-trait = { workspace=true }
once_cell = { workspace=true }
egui_json_tree = { workspace = true }
brotli = { workspace=true }
base64 = { workspace=true }
egui_plot = { workspace = true }
dunce = "1.0.5"
directories = "6.0.0"
image-meta = "0.1.4"
indexmap = { version = "2.10.0", features = ["serde"] }



[dependencies.egui]
version = "0.32.0"
default-features = false
features = ["rayon", "bytemuck", "log"]

[dependencies.crossterm]
version = "0.28.1"
features = ["event-stream"]

# gfx-hal = { version = "0.9.0", features = ["serde"] }
# egui_tracing = "0.2.2"
# portable-pty = "0.8.1"
# 
# known-folders 
# robocopyrs 


[target.'cfg(target_os = "windows")'.dependencies]
windows = {version = "0.61", features = [
    "Win32_System",
    "Win32",
    "Win32_System_Com",
    "Win32_System_UpdateAgent",
    "Win32_System_Shutdown",
    "Win32_System_Threading",
    "Win32_Security",
    "Win32_System_Ole",
    "Win32_System_Variant",
    "Win32_System_SecurityCenter",
    "Win32_System_Registry",
    "Storage",
    "Win32_NetworkManagement_Ndis",
    "Win32_Networking_WinSock", 
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_WiFi",
    "Win32_System_Diagnostics",
    "Win32_Devices",
    "Win32_Devices_DeviceAndDriverInstallation",
    "Win32_Devices_Properties"
]}
windows-registry = "0.5"
windows-core = "0.61"
windows_x86_64_msvc = "0.53"
winapi = { version = "0.3", features = ["processthreadsapi"] }
memmap2 = "0.9"
breakpad-symbols = { version = "0.26.0" }
minidump = { version = "0.26.0" }
minidump-common = { version = "0.26.0" }
minidump-processor = { version = "0.26.0", features = ["http"] }
minidump-unwind = "0.26.0"
wmi = "0.17.0"
evtx = "0.8"

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }
openssl-sys = "0.9"
# libatasmart = "0.3.1"


[dev-dependencies]
criterion = { version = "0.6", features = ["async_tokio"]}

[[bench]]
name = "file_copy_benchmark"
harness = false


[target.'cfg(target_os = "windows")'.build-dependencies]
static_vcruntime = "2"
embed-resource = "3.0.1"
winres = "0.1"
# embed-manifest = "1.4.0"

[package.metadata]
icon = ["D:/Users/Owner/Documents/GitHub/Mastertech4.0/src/assets/masterlogoV2.ico"]
resources = ["src/assets/**/*png", "src/assets/**/*ico"]


