[target.x86_64-apple-ios]
linker = "/usr/lib/swift/bin/clang"
rustflags = [
  "-C", "link-arg=-fuse-ld=lld",
  "-C", "link-arg=--ld-path=/home/shadowbroker/.swiftpm/swift-sdks/darwin.artifactbundle/toolset/bin/ld64.lld",
]

[target.aarch64-apple-ios]
linker = "/usr/lib/swift/bin/clang"
rustflags = [
  "-C", "link-arg=-fuse-ld=lld",
  "-C", "link-arg=--ld-path=/home/shadowbroker/.swiftpm/swift-sdks/darwin.artifactbundle/toolset/bin/ld64.lld",
]
