[package]
name = "qc_app"
version = "0.1.0"
edition = "2024"
description = "Mastertech QC"
build = "build.rs"

[package.metadata]
icon = ["src/assets/QcApp.ico"]
resources = ["src/assets/**/*png", "src/assets/**/*ico"]

[dependencies]
eframe = { version = "0.34", features = ["persistence", "serde", "default_fonts", "glow"], default-features = false }
rustls = { version = "0.23", default-features = false, features = ["ring"] }
egui_plot = { workspace = true }
web-time = { workspace = true }
stress-kit.workspace = true
stress-runner.workspace = true
database.workspace = true
egui-data-table.workspace = true
egui_extras.workspace = true
egui-phosphor = { version = "0.12.0", default-features = false, features = ["regular"] }
sysinfo = { version = "0.39", features = ["serde", "multithread"] }
log.workspace = true
anyhow.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
rmcp.workspace = true
axum.workspace = true
crossbeam.workspace = true
once_cell.workspace = true
directories = "6.0.0"
env_logger = "*"
reqwest = { version = "0.13.2", default-features = false, features = ["json", "rustls"] }
rusqlite = { version = "0.39.0", features = ["bundled"] }
image = "0.25"
sha2 = "0.10"
hex = "0.4"

[target.'cfg(any(target_os = "linux", target_os = "freebsd", target_os = "openbsd", target_os = "netbsd"))'.dependencies]
eframe = { version = "0.34", features = ["x11", "wayland"], default-features = false }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62", features = [
    "Win32_System",
    "Win32",
    "Win32_System_Threading",
]}

[dependencies.egui]
version = "0.34"
default-features = false
features = ["rayon", "bytemuck"]

[target.'cfg(target_os = "windows")'.build-dependencies]
dotenvy = { workspace = true }
static_vcruntime = "3"
embed-resource = "3"
winres = "0.1"

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }
openssl-sys = "0.9"
