[package]
name = "mastertech-mobile"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { git = "https://github.com/DioxusLabs/dioxus", tag = "v0.7.0-rc.0", features = ["router"] }
# dioxus-router = { git = "https://github.com/DioxusLabs/dioxus", tag = "v0.7.0-rc.0", package = "dioxus-router", features = ["wasm-split"] }
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
anyhow.workspace = true
log.workspace = true
surrealdb.workspace = true
database.workspace = true
crossbeam-channel = "0.5"
futures-timer = "3"
dirs = "5"

[features]
default = ["mobile"]
# The feature that are only required for the web = ["dioxus/web"] build target should be optional and only enabled in the web = ["dioxus/web"] feature
web = ["dioxus/web"]
# The feature that are only required for the desktop = ["dioxus/desktop"] build target should be optional and only enabled in the desktop = ["dioxus/desktop"] feature
desktop = ["dioxus/desktop"]
# The feature that are only required for the mobile = ["dioxus/mobile"] build target should be optional and only enabled in the mobile = ["dioxus/mobile"] feature
mobile = ["dioxus/mobile"]
