[package]
name = "mtechserver"
version = "2.3.3"
edition = "2024"

# [[bin]]
# name = "mtechserver"
# path = "src/mtechserver.rs"

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "webworker"
path = "src/webworker.rs"

[[bin]]
name = "deser_worker"
path = "src/deser_worker.rs"

[dependencies]
zstd = "0.13"
gloo-worker = "0.5"
gloo-net = { version = "0.6", features = ["http"]}
web-sys = { version = "0.3", features = ["Storage", "Window", "Location", "HtmlCanvasElement", "CacheStorage"] }
ewebsock = { git = "https://github.com/shadowbrok3r/ewebsock.git", version = "0.9.1", features = ["tls"]}
reqwest = { version = "0.12", features = ["stream", "json"] }
displays = { path="../displays", features = ["wasm"]}

surrealdb-alpha ={ workspace = true }
# surrealdb = { workspace=true }
wasm-cookies = { workspace = true }
egui_plot = { workspace = true }
brotli = { workspace=true }
base64 = { workspace=true }
wasm-bindgen-futures = { workspace=true }
web-time = { workspace=true }
wasm-bindgen = { workspace=true }
database = { workspace=true }
log  = { workspace=true }
serde = { workspace=true }
chrono = { workspace=true }
serde_json = { workspace=true }
egui_extras = { workspace=true }
egui_dock = { workspace=true }
anyhow = { workspace=true }
eframe = { workspace=true }
crossbeam = { workspace=true }
futures = { workspace=true }
rfd = { workspace=true }
gloo-console = { workspace=true }
egui-data-table = { workspace=true }
bincode = { workspace = true }
itertools = { workspace = true }

[dependencies.uuid]
version = "1.13"
features = ["v4", "rng-getrandom"]

[dependencies.getrandom_v03]
package = "getrandom"
version = "0.3"
features = ["wasm_js"]

[dependencies.getrandom_v02]
package = "getrandom"
version = "0.2"
features = ["js"]

