[package]
name = "mtechserver"
version = "2.0.11"
edition = "2021"

# [[bin]]
# name = "mtechserver"
# path = "src/mtechserver.rs"

[lib]
crate-type = ["cdylib"]

# [[bin]]
# name = "worker"
# path = "src/worker.rs"

[dependencies]
console_error_panic_hook = "0.1"
gloo-worker = "0.5"
# gloo-timers = { version = "0.3", features = ["futures"]}
js-sys = "0.3"
gloo-net = { version = "0.6", features = ["http"]}
web-sys = { version = "0.3", features = ["Storage", "Window", "Location", "HtmlCanvasElement"] }
wasm-cookies = { version= "0.2" }
ewebsock = "0.8"
egui_plot = "0.29"
rusty-s3 = { version = "0.5", features = ["wasm_bindgen"] } # default-features = false
async-openai-wasm = { version = "0.25" }
derive_more = {version = "1", features = ["from"]}
rpc-router = "0.1"
schemars = "0.8"
reqwest = { version = "0.12", features = ["stream", "json"] }
displays = { path="../displays", features = ["wasm"]}

egui_json_tree = { workspace = true }
wasm-bindgen-futures = { workspace=true }
web-time = { workspace=true }
wasm-bindgen = { workspace=true }
egui_struct = { workspace=true }
database = { workspace=true }
surrealdb = { workspace=true }
mime_guess = { workspace=true }
structdiff = { workspace=true }
once_cell = { workspace=true }
async-trait = { workspace=true }
bytes = { workspace=true }
log  = { workspace=true }
serde = { workspace=true }
chrono = { workspace=true }
# dotenv = { workspace=true }
serde_json = { workspace=true }
egui_extras = { workspace=true }
egui_dock = { workspace=true }
anyhow = { workspace=true }
eframe = { workspace=true }
ratatui = { workspace=true }
crossbeam = { workspace=true }
futures = { workspace=true }
fuzzy-matcher = { workspace=true }
uuid = { workspace=true }
bincode = { workspace=true }
rfd = { workspace=true }
regex = { workspace=true }
gloo-console = { workspace=true }
# [target.'cfg(target_arch = "wasm32")'.dependencies]
# wasm_thread = "0.3"
# rayon = "1.8"
# wasm-bindgen-rayon = {version="1.2", features=["no-bundler"]}
# egui_ratatui = { workspace=true }
# ratframe = { workspace=true }




