[package]
name = "mtechserver"
version = "2.1.6"
edition = "2024"

# [[bin]]
# name = "mtechserver"
# path = "src/mtechserver.rs"

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "webworker"
path = "src/webworker.rs"

[[bin]]
name = "deser_worker"
path = "src/deser_worker.rs"

[dependencies]
gloo-worker = "0.5"
gloo-net = { version = "0.6", features = ["http"]}
web-sys = { version = "0.3", features = ["Storage", "Window", "Location", "HtmlCanvasElement"] }
wasm-cookies = { version= "0.2" }
ewebsock = "0.8"
reqwest = { version = "0.12", features = ["stream", "json"] }
displays = { path="../displays", features = ["wasm"]}
egui_plot = { workspace = true }
brotli = { workspace=true }
base64 = { workspace=true }
wasm-bindgen-futures = { workspace=true }
web-time = { workspace=true }
wasm-bindgen = { workspace=true }
database = { workspace=true }
surrealdb = { workspace=true }
log  = { workspace=true }
serde = { workspace=true }
chrono = { workspace=true }
serde_json = { workspace=true }
egui_extras = { workspace=true }
egui_dock = { workspace=true }
anyhow = { workspace=true }
eframe = { workspace=true }
crossbeam = { workspace=true }
futures = { workspace=true }
rfd = { workspace=true }
gloo-console = { workspace=true }



