[package]
name = "database"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
xml = "1"
# surrealdb-alpha ={ workspace = true }
surrealdb = { workspace=true }
serde_json = { workspace=true }
web-time = { workspace=true }
crossbeam = { workspace=true }
async-trait = { workspace=true }
once_cell = { workspace=true }
structdiff = { workspace=true }
anyhow = { workspace=true }
rusty-s3 = { workspace=true }
futures = { workspace=true }
regex = { workspace=true }
chrono = {workspace=true}
serde = { workspace=true }
bytes = {workspace = true}
brotli = { workspace=true }
rfd = { workspace = true }
log = { workspace=true }
fuzzy-matcher = { workspace=true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = { workspace=true }