# cargo-features = ["per-package-target"]
[package]
name = "database"
version = "0.1.0"
edition = "2021"
# forced-target = "wasm32-unknown-unknown"

[dependencies]
serde_json = { workspace=true }
dotenv = { workspace=true }
serde = { workspace=true }
log = { workspace=true }
anyhow = { workspace=true }
# surrealdb-alpha = { workspace=true }
surrealdb = { workspace=true }
uuid = { version = "1.8.0", features = ["v4"] }
