//! Global crossbeam channels that bridge MCP tool calls (`displays`) to the
//! host application's Scripts tab (`Mastertech4.0` egui or terminal mode).
//!
//! Pattern: same shape as `WASM_LOAD_CHANNEL` and `REMOTE_TOOL_CALL_CHANNEL`
//! in `crate::plugins`. The MCP server pushes a `ScriptRunRequest` and waits
//! on the matching `ScriptRunResult` (correlated by `request_id`). Mastertech
//! drains the request channel each frame / tick, runs the script through its
//! existing handlers, then publishes the result + collected log lines back.
//!
//! Why crossbeam globals instead of `Arc` / DI: the MCP server is constructed
//! by the host (`Mastertech4.0::main`) but the host has no handle to the live
//! MCP `PluginToolProvider`; pre-existing channel slots avoid that wiring.

use super::ScriptCategory;
use crossbeam::channel::{Receiver, Sender};
use once_cell::sync::Lazy;
use serde::{Deserialize, Serialize};

/// Request from MCP → host Scripts tab to execute a single named script.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScriptRunRequest {
    /// UUID generated by the MCP tool. The host echoes it back in the result
    /// so the MCP can correlate concurrent calls.
    pub request_id: String,
    /// Category bucket the script lives in. Matches `ScriptCategory` so the
    /// host can look it up in its existing `ScriptsState.categories` map.
    pub category: ScriptCategory,
    /// Script display name as shown in `displays::scripts::categories`
    /// (e.g. "Activate Webroot", "Disable OneDrive Startup").
    pub script_name: String,
    /// Optional service number override. If `Some`, the host should set this
    /// in the Scripts tab field before running activation scripts.
    pub service_number: Option<String>,
    /// Optional customer email override (needed by SEB activation).
    pub customer_email: Option<String>,
    /// Optional diagnostic_session id to link stress_test_run.session_ref.
    #[serde(default)]
    pub diagnostic_session_id: Option<String>,
}

/// Result published by the host back to MCP when a script finishes.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScriptRunResult {
    pub request_id: String,
    /// `success` mirrors the Scripts tab's pass/fail state — true if the
    /// script reported completion without an error.
    pub success: bool,
    /// One-line summary message ("Webroot installed successfully", etc.).
    pub message: String,
    /// Structured log lines captured during execution. The host should drain
    /// any log entries that were emitted between request_received and
    /// completion and include them here so the AI sees what happened.
    pub logs: Vec<String>,
}

static SCRIPT_RUN_REQUEST_CHANNEL: Lazy<(Sender<ScriptRunRequest>, Receiver<ScriptRunRequest>)> =
    Lazy::new(crossbeam::channel::unbounded);

static SCRIPT_RUN_RESULT_CHANNEL: Lazy<(Sender<ScriptRunResult>, Receiver<ScriptRunResult>)> =
    Lazy::new(crossbeam::channel::unbounded);

/// Get a cloneable sender for the request channel. Used by the MCP `scripts_run`
/// tool to push a request that the host's Scripts tab will pick up.
pub fn script_run_request_sender() -> Sender<ScriptRunRequest> {
    SCRIPT_RUN_REQUEST_CHANNEL.0.clone()
}

/// Get a cloneable receiver for the request channel. Called by the host's
/// Scripts tab (egui or terminal) once per frame/tick to drain pending MCP
/// requests.
pub fn script_run_request_receiver() -> Receiver<ScriptRunRequest> {
    SCRIPT_RUN_REQUEST_CHANNEL.1.clone()
}

/// Get a cloneable sender for the result channel. Used by the host's Scripts
/// tab to publish completion results back to MCP.
pub fn script_run_result_sender() -> Sender<ScriptRunResult> {
    SCRIPT_RUN_RESULT_CHANNEL.0.clone()
}

/// Get a cloneable receiver for the result channel. Used by the MCP
/// `scripts_run` tool to await the result for a specific `request_id`.
pub fn script_run_result_receiver() -> Receiver<ScriptRunResult> {
    SCRIPT_RUN_RESULT_CHANNEL.1.clone()
}
