apiVersion: v1
kind: PersistentVolume
metadata:
  name: surrealdb-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path 
  hostPath: 
    path: "/SurrealDB"