apiVersion: v1
kind: PersistentVolume
metadata:
  name: surreal-buckets-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: "/SurrealBuckets"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: surreal-buckets-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
  volumeName: surreal-buckets-pv