# [target.wasm32-unknown-unknown]
# rustflags = [ "-C", "target-feature=+atomics,+bulk-memory,+mutable-globals", '--cfg', 'getrandom_backend="wasm_js"'] # , "-Awarnings" "--cfg=web_sys_unstable_apis",
# [build]
# target = [ "wasm32-unknown-unknown"]

# [unstable]
# build-std = ["std,panic_abort"]
