//! Instruction-cache stressor.
//!
//! Idea: build many distinct function pointers and dispatch through them in
//! a pseudo-random order. Each function does a small amount of independent
//! work, so the hot path is the *indirect call + i-cache miss*. The fan-out
//! `MANY_FN` is chosen to spill modern L1i (32–64 KiB) but stay friendly to
//! L2.
//!
//! Reports Mcall/s (millions of indirect calls per second).
//!
//! The 64 functions are generated by macro to keep the per-function code
//! body identical (and tiny). The compiler will likely inline each one as a
//! few ALU ops, but the dispatch table forces an indirect call.

use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::{mpsc, Arc};
use std::thread;
use std::time::{Duration, Instant};

use crate::Metrics;

const CALLS_PER_BURST: u64 = 200_000;
const TICK: Duration = Duration::from_millis(500);
const MANY_FN: usize = 64;

type Op = fn(u64) -> u64;

macro_rules! op {
    ($name:ident, $tag:expr) => {
        #[inline(never)]
        fn $name(x: u64) -> u64 {
            // Each variant uses the same shape but a unique tag so codegen
            // can't merge them into one.
            let t: u64 = $tag;
            let y = x.rotate_left((t & 63) as u32) ^ t;
            y.wrapping_add(t).wrapping_mul(0x9E37_79B9_7F4A_7C15)
        }
    };
}

op!(op00, 0x00); op!(op01, 0x01); op!(op02, 0x02); op!(op03, 0x03);
op!(op04, 0x04); op!(op05, 0x05); op!(op06, 0x06); op!(op07, 0x07);
op!(op08, 0x08); op!(op09, 0x09); op!(op0a, 0x0a); op!(op0b, 0x0b);
op!(op0c, 0x0c); op!(op0d, 0x0d); op!(op0e, 0x0e); op!(op0f, 0x0f);
op!(op10, 0x10); op!(op11, 0x11); op!(op12, 0x12); op!(op13, 0x13);
op!(op14, 0x14); op!(op15, 0x15); op!(op16, 0x16); op!(op17, 0x17);
op!(op18, 0x18); op!(op19, 0x19); op!(op1a, 0x1a); op!(op1b, 0x1b);
op!(op1c, 0x1c); op!(op1d, 0x1d); op!(op1e, 0x1e); op!(op1f, 0x1f);
op!(op20, 0x20); op!(op21, 0x21); op!(op22, 0x22); op!(op23, 0x23);
op!(op24, 0x24); op!(op25, 0x25); op!(op26, 0x26); op!(op27, 0x27);
op!(op28, 0x28); op!(op29, 0x29); op!(op2a, 0x2a); op!(op2b, 0x2b);
op!(op2c, 0x2c); op!(op2d, 0x2d); op!(op2e, 0x2e); op!(op2f, 0x2f);
op!(op30, 0x30); op!(op31, 0x31); op!(op32, 0x32); op!(op33, 0x33);
op!(op34, 0x34); op!(op35, 0x35); op!(op36, 0x36); op!(op37, 0x37);
op!(op38, 0x38); op!(op39, 0x39); op!(op3a, 0x3a); op!(op3b, 0x3b);
op!(op3c, 0x3c); op!(op3d, 0x3d); op!(op3e, 0x3e); op!(op3f, 0x3f);

static OPS: [Op; MANY_FN] = [
    op00, op01, op02, op03, op04, op05, op06, op07,
    op08, op09, op0a, op0b, op0c, op0d, op0e, op0f,
    op10, op11, op12, op13, op14, op15, op16, op17,
    op18, op19, op1a, op1b, op1c, op1d, op1e, op1f,
    op20, op21, op22, op23, op24, op25, op26, op27,
    op28, op29, op2a, op2b, op2c, op2d, op2e, op2f,
    op30, op31, op32, op33, op34, op35, op36, op37,
    op38, op39, op3a, op3b, op3c, op3d, op3e, op3f,
];

pub(crate) fn run(
    thread_count: usize,
    cancel: &Arc<AtomicBool>,
    tx: &mpsc::Sender<Metrics>,
    started_at: Instant,
) {
    let calls_counter = Arc::new(AtomicU64::new(0));

    let handles: Vec<_> = (0..thread_count)
        .enumerate()
        .map(|(id, _)| {
            let cancel = cancel.clone();
            let counter = calls_counter.clone();
            thread::Builder::new()
                .name("stress-kit-icache".into())
                .spawn(move || icache_worker(id as u64, cancel, counter))
                .expect("stress-kit: failed to spawn icache worker")
        })
        .collect();

    let mut last_tick = Instant::now();
    let mut last_count: u64 = 0;

    while !cancel.load(Ordering::Relaxed) {
        thread::sleep(Duration::from_millis(50));
        if last_tick.elapsed() >= TICK {
            let now = calls_counter.load(Ordering::Relaxed);
            let delta = now.saturating_sub(last_count);
            let delta_secs = last_tick.elapsed().as_secs_f64().max(f64::EPSILON);
            let mcall = (delta as f64) / delta_secs / 1e6;

            let _ = tx.send(Metrics {
                elapsed_secs: started_at.elapsed().as_secs_f64(),
                throughput: mcall,
                last_error: None,
            });

            last_count = now;
            last_tick = Instant::now();
        }
    }

    for h in handles {
        let _ = h.join();
    }
}

fn icache_worker(seed: u64, cancel: Arc<AtomicBool>, counter: Arc<AtomicU64>) {
    let mut state: u64 = 0xA5A5_5A5A_DEAD_BEEF ^ seed;
    let mut acc: u64 = 0;
    while !cancel.load(Ordering::Relaxed) {
        for _ in 0..CALLS_PER_BURST {
            state = state.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
            let idx = (state >> 24) as usize % MANY_FN;
            // Indirect call through the OPS table — defeats devirtualization
            // and keeps the i-cache footprint wide.
            acc ^= (OPS[idx])(state);
        }
        std::hint::black_box(acc);
        counter.fetch_add(CALLS_PER_BURST, Ordering::Relaxed);
    }
}
