[package]
name = "displays"
version = "0.1.0"
edition = "2021"

[dependencies]
parking_lot = "0.12"
ewebsock = "0.6"
zstd = "0.13"
bincode = { workspace=true } 
anyhow = { workspace=true }
database = { workspace=true }
eframe = { workspace=true }
log = { workspace=true }
serde = { workspace=true }
fuzzy-matcher = { workspace=true }
surrealdb = { workspace=true }
egui_extras = { workspace=true }
chrono = { workspace=true }
serde_json = { workspace=true }
crossbeam = { workspace=true }
