[package]
name = "surreal_client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-cron-scheduler = "0.13.0"
sha2 = { version = "0.10", features = ["std"] }
hex = "0.4.3"
sysinfo = "0.33"
num-format = "0.4"
# MasterTech = {path="../Mastertech4.0"}
anyhow = { workspace = true }
database = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
simplelog = { workspace = true }
uuid = { workspace = true }
futures = { workspace = true }
surrealdb = { workspace = true }
log = { workspace = true }
regex = { workspace=true }