on: [push, pull_request, workflow_dispatch]

name: CI

env:
  RUSTFLAGS: -C target-feature=+crt-static

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        include:
        # - os: macos-latest
        #   TARGET: x86_64-apple-darwin

        # - os: ubuntu-latest
        #   TARGET: x86_64-unknown-linux-musl

        - os: windows-latest
          TARGET: x86_64-pc-windows-msvc
          EXTENSION: .exe

    steps:
    - name: Building ${{ matrix.TARGET }}
      run: echo "${{ matrix.TARGET }}"
      
    - name: Set Env
      run: echo "{name}={value}" >> $GITHUB_ENV

    - name: Extract version from Cargo.toml
      id: foo
      uses: dante-signal31/rust-app-version@v1.2.0
      with:
        cargo_toml_folder: ./
         
      
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1.0.1
      with:
        toolchain: stable
        target: ${{ matrix.TARGET }}
        override: true

    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --verbose --release --target=${{ matrix.TARGET }}

    - name: Rename
      run: cp target/${{ matrix.TARGET }}/release/MasterTech${{ matrix.EXTENSION }} Mastertech${{ matrix.EXTENSION }} # ${{ matrix.TARGET }}

    - uses: actions/upload-artifact@master
      with:
        name: Mastertech${{ matrix.EXTENSION }} # ${{ matrix.TARGET }}
        path: Mastertech${{ matrix.EXTENSION }} # ${{ matrix.TARGET }}

    - name: Create tag
      if: ${{ github.event_name == 'push' }}
      run: |
        git tag v${{ steps.foo.outputs.app_version }}
        git push origin v${{ steps.foo.outputs.app_version }}

    - uses: svenstaro/upload-release-action@v2
      name: Upload binaries to release
      if: ${{ github.event_name == 'push' }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Mastertech-${{ matrix.EXTENSION }} # ${{ matrix.TARGET }}
        asset_name: Mastertech-${{ matrix.EXTENSION }} # ${{ matrix.TARGET }}
        tag: v${{ steps.foo.outputs.app_version }}
        # prerelease: ${{ !startsWith(github.ref, 'refs/tags/') }}
        overwrite: true

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.foo.outputs.app_version }}
        release_name: Mastertech v${{ steps.foo.outputs.app_version }}
        body: |
          ${{ steps.Changelog.outputs.changelog }}
        draft: false
        prerelease: false

    - name: Changelog
      uses: scottbrenner/generate-changelog-action@master
      id: Changelog
      env:
        REPO: ${{ github.repository }}
